# Generated by Django 4.0.5 on 2022-12-25 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_programs_studyfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceExamination',
            fields=[
                ('entranceexam_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('writingDate', models.DateTimeField()),
                ('deadlineDate', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='programs',
            name='id',
        ),
        migrations.AddField(
            model_name='programs',
            name='program_id',
            field=models.AutoField(default=1, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
