# Generated by Django 4.0.5 on 2022-12-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_entranceexamination_remove_programs_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='program_id',
        ),
        migrations.AddField(
            model_name='programs',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
