# Generated by Django 4.0.5 on 2022-12-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_remove_programs_program_id_programs_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('name', models.CharField(blank=True, max_length=255)),
                ('duration', models.IntegerField(blank=True)),
                ('program_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Programs',
        ),
    ]
