# Generated by Django 4.0.5 on 2023-01-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
