# Generated by Django 4.0.5 on 2023-02-01 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_school_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyfield',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyfield',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
