export const FIELD_OF_STUDY_REQUEST = 'FIELD_OF_STUDY_REQUEST'
export const FIELD_OF_STUDY_SUCCESS = 'FIELD_OF_STUDY_SUCCESS'
export const FIELD_OF_STUDY_FAIL = 'FIELD_OF_STUDY_FAIL'

export const FIELD_OF_STUDY_DETAILS_REQUEST = 'FIELD_OF_STUDY_DETAILS_REQUEST'
export const FIELD_OF_STUDY_DETAILS_SUCCESS = 'FIELD_OF_STUDY_DETAILS_SUCCESS'
export const FIELD_OF_STUDY_DETAILS_FAIL = 'FIELD_OF_STUDY_DETAILS_FAIL'