export const SCHOOL_LIST_REQUEST = 'SCHOOL_LIST_REQUEST'
export const SCHOOL_lIST_SUCCESS = 'SCHOOL_LIST_SUCCESS'
export const SCHOOL_LIST_FAIL = 'SCHOOL_LIST_FAIL'

export const SCHOOL_DETAILS_REQUEST = 'SCHOOL_DETAILS_REQUEST'
export const SCHOOL_DETAILS_SUCCESS = 'SCHOOL_DETAILS_SUCCESS'
export const SCHOOL_DETAILS_FAIL = 'SCHOOL_DETAILS_FAIL'